version: '2'
services:
  server:
    build: .
    command: java -jar /app/busa-server-0.1.0-SNAPSHOT-standalone.jar
    volumes:
      - ../:/code
    ports:
      - "3000:3000"

  db:
    image: rethinkdb
    ports:
      - "8080:8080"
